import _ from 'lodash'
import ICONS from './icons'

export default [
  {
    "cost": 0,
    "race": "HUMAN",
    "serialNumber": 1,
    "type": "AGENT",
    "attack": 1,
    "defense": "2",
    "effect": "BEHIND ATTACK + 2",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 0,
    "race": "HUMAN",
    "serialNumber": 2,
    "type": "AGENT",
    "attack": 2,
    "defense": "2",
    "effect": "none",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 0,
    "race": "HUMAN",
    "serialNumber": 3,
    "type": "AGENT",
    "attack": 1,
    "defense": "0",
    "effect": "AHEAD ATTACK + T",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 0,
    "race": "HUMAN",
    "serialNumber": 4,
    "type": "AGENT",
    "attack": 2,
    "defense": "0",
    "effect": "TWICE",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 0,
    "race": "HUMAN",
    "serialNumber": 5,
    "type": "AGENT",
    "attack": 1,
    "defense": 2,
    "effect": "QUICK",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 0,
    "race": "HUMAN",
    "serialNumber": 6,
    "type": "AGENT",
    "attack": 1,
    "defense": "T+1",
    "effect": "BEHIND RANGE + 1",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 0,
    "race": "HUMAN",
    "serialNumber": 7,
    "type": "AGENT",
    "attack": 1,
    "defense": "0",
    "effect": "AHEAD DEFENSE + 4",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 0,
    "race": "HUMAN",
    "serialNumber": 8,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "none",
    "attackBonus": "QUICK",
    "defenseBonus": "DEFENSE LETHAL"
  },
  {
    "cost": 0,
    "race": "HUMAN",
    "serialNumber": 9,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "RECRUIT 1 / TRAIN 1",
    "attackBonus": "ATTACK + 1",
    "defenseBonus": "DEFENSE + 2"
  },
  {
    "cost": 0,
    "race": "HUMAN",
    "serialNumber": 10,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "TRAIN 1",
    "attackBonus": "TWICE",
    "defenseBonus": "DEFENSE X2"
  },
  {
    "cost": 0,
    "race": "HUMAN",
    "serialNumber": 11,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "none",
    "attackBonus": "RANGE + 1",
    "defenseBonus": "TOUGH"
  },
  {
    "cost": 0,
    "race": "HUMAN",
    "serialNumber": 12,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "none",
    "attackBonus": "QUICK",
    "defenseBonus": "TOUGH"
  },
  {
    "cost": 0,
    "race": "HUMAN",
    "serialNumber": 13,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "RECRUIT 1",
    "attackBonus": "ATTACK + 2",
    "defenseBonus": "DEFENSE + 3"
  },
  {
    "cost": 0,
    "race": "HUMAN",
    "serialNumber": 14,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "none",
    "attackBonus": "RANGE + 1",
    "defenseBonus": "DEFENSE + 4"
  },
  {
    "cost": 1,
    "race": "HUMAN",
    "serialNumber": 1,
    "type": "AGENT",
    "attack": "4",
    "defense": "T+1",
    "effect": "none",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 1,
    "race": "HUMAN",
    "serialNumber": 2,
    "type": "AGENT",
    "attack": "T",
    "defense": "2",
    "effect": "DEFENSE LETHAL",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 1,
    "race": "HUMAN",
    "serialNumber": 3,
    "type": "AGENT",
    "attack": "T+1",
    "defense": "1",
    "effect": "RANGE = 2",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 1,
    "race": "HUMAN",
    "serialNumber": 4,
    "type": "AGENT",
    "attack": "1",
    "defense": "T+3",
    "effect": "BEHIND QUICK",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 1,
    "race": "HUMAN",
    "serialNumber": 5,
    "type": "AGENT",
    "attack": "T",
    "defense": "1",
    "effect": "AHEAD ATTACK + 4",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 1,
    "race": "HUMAN",
    "serialNumber": 6,
    "type": "AGENT",
    "attack": "2",
    "defense": "T+1",
    "effect": "AHEAD RANGE + 1",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 1,
    "race": "HUMAN",
    "serialNumber": 7,
    "type": "AGENT",
    "attack": "T+1",
    "defense": "0",
    "effect": "AHEAD DEFENSE + 5",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 1,
    "race": "HUMAN",
    "serialNumber": 8,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "RECRUIT 2 / TRAIN 2",
    "attackBonus": "QUICK",
    "defenseBonus": "TOUGH"
  },
  {
    "cost": 1,
    "race": "HUMAN",
    "serialNumber": 9,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "RECRUIT 1",
    "attackBonus": "ATTACK LETHAL",
    "defenseBonus": "DEFENSE + 6"
  },
  {
    "cost": 1,
    "race": "HUMAN",
    "serialNumber": 10,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "RECRUIT 2 / TRAIN 2",
    "attackBonus": "RANGE + 1",
    "defenseBonus": "DEFENSE X2"
  },
  {
    "cost": 1,
    "race": "HUMAN",
    "serialNumber": 11,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "RECRUIT 2 / TRAIN 2",
    "attackBonus": "QUICK",
    "defenseBonus": "DEFENSE X2"
  },
  {
    "cost": 1,
    "race": "HUMAN",
    "serialNumber": 12,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "RECRUIT 2 / TRAIN 2",
    "attackBonus": "TWICE",
    "defenseBonus": "DEFENSE LETHAL"
  },
  {
    "cost": 1,
    "race": "HUMAN",
    "serialNumber": 13,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "none",
    "attackBonus": "ATTACK + 3",
    "defenseBonus": "LIFE"
  },
  {
    "cost": 1,
    "race": "HUMAN",
    "serialNumber": 14,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "RECRUIT 1 / TRAIN 1",
    "attackBonus": "RANGE + 2",
    "defenseBonus": "DEFENSE + 5"
  },
  {
    "cost": 2,
    "race": "HUMAN",
    "serialNumber": 1,
    "type": "AGENT",
    "attack": "T+3",
    "defense": "6",
    "effect": "none",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 2,
    "race": "HUMAN",
    "serialNumber": 2,
    "type": "AGENT",
    "attack": "3",
    "defense": "T+2",
    "effect": "ATTACK LETHAL",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 2,
    "race": "HUMAN",
    "serialNumber": 3,
    "type": "AGENT",
    "attack": "T+2",
    "defense": "3",
    "effect": "QUICK",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 2,
    "race": "HUMAN",
    "serialNumber": 4,
    "type": "AGENT",
    "attack": "4",
    "defense": "T",
    "effect": "AHEAD ATTACK X2",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 2,
    "race": "HUMAN",
    "serialNumber": 5,
    "type": "AGENT",
    "attack": "2",
    "defense": "T+5",
    "effect": "BEHIND RANGE + 2",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 2,
    "race": "HUMAN",
    "serialNumber": 6,
    "type": "AGENT",
    "attack": "2T",
    "defense": "1",
    "effect": "AHEAD DEFENSE LETHAL",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 2,
    "race": "HUMAN",
    "serialNumber": 7,
    "type": "AGENT",
    "attack": "T+1",
    "defense": "8",
    "effect": "BEHIND TWICE",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": 2,
    "race": "HUMAN",
    "serialNumber": 8,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "RECRUIT 2 / TRAIN 1",
    "attackBonus": "ATTACK + 5",
    "defenseBonus": "LIFE"
  },
  {
    "cost": 2,
    "race": "HUMAN",
    "serialNumber": 9,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "RECRUIT 2 / TRAIN 2",
    "attackBonus": "ATTACK LETHAL",
    "defenseBonus": "LIFE"
  },
  {
    "cost": 2,
    "race": "HUMAN",
    "serialNumber": 10,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "RECRUIT 2 / TRAIN 2",
    "attackBonus": "ATTACK X2",
    "defenseBonus": "LIFE"
  },
  {
    "cost": 2,
    "race": "HUMAN",
    "serialNumber": 11,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "RECRUIT 5 / TRAIN 4",
    "attackBonus": "QUICK",
    "defenseBonus": "DEFENSE X2"
  },
  {
    "cost": 2,
    "race": "HUMAN",
    "serialNumber": 12,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "RECRUIT 4 / TRAIN 3",
    "attackBonus": "RANGE + 2",
    "defenseBonus": "DEFENSE LETHAL"
  },
  {
    "cost": 2,
    "race": "HUMAN",
    "serialNumber": 13,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "RECRUIT 1 / DRAW 1",
    "attackBonus": "TWICE",
    "defenseBonus": "LIFE"
  },
  {
    "cost": 2,
    "race": "HUMAN",
    "serialNumber": 14,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "DRAW 3 / DISCARD 1",
    "attackBonus": "RANGE + 1",
    "defenseBonus": "DEFENSE + 4"
  },
  {
    "cost": "1",
    "race": "MECHA",
    "serialNumber": 1,
    "type": "AGENT",
    "attack": 1,
    "defense": 2,
    "effect": "ATTACK LETHAL",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": "1",
    "race": "MECHA",
    "serialNumber": 2,
    "type": "AGENT",
    "attack": 3,
    "defense": 1,
    "effect": "QUICK",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": "1",
    "race": "MECHA",
    "serialNumber": 3,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "Draw 1 card. Your opponent's warden gains 1 health (their choice).",
    "attackBonus": "TWICE",
    "defenseBonus": "TOUGH"
  },
  {
    "cost": "2",
    "race": "MECHA",
    "serialNumber": 1,
    "type": "AGENT",
    "attack": 4,
    "defense": 0,
    "effect": "TWICE / RANGE = 2",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": "2",
    "race": "MECHA",
    "serialNumber": 2,
    "type": "AGENT",
    "attack": 3,
    "defense": 5,
    "effect": "QUICK",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": "2",
    "race": "MECHA",
    "serialNumber": 3,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": <span>Play any human card while reducing its discard cost by 1. If you play a <ICONS.Discard/>0, draw 1 card.</span>,
    "attackBonus": "ATTACK X2",
    "defenseBonus": "DEFENSE + 6"
  },
  {
    "cost": "3",
    "race": "MECHA",
    "serialNumber": 1,
    "type": "AGENT",
    "attack": 7,
    "defense": 0,
    "effect": "QUICK",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": "3",
    "race": "MECHA",
    "serialNumber": 2,
    "type": "AGENT",
    "attack": 4,
    "defense": 4,
    "effect": "RANGE = 2 / DEFENSE LETHAL",
    "attackBonus": null,
    "defenseBonus": null
  },
  {
    "cost": "3",
    "race": "MECHA",
    "serialNumber": 3,
    "type": "ALLY",
    "attack": null,
    "defense": null,
    "effect": "Opponent draws 1 card. Play any human card without cost.",
    "attackBonus": "ATTACK + 5",
    "defenseBonus": "LIFE"
  }
]
