export default [
  {
    id: "army-celestial-knights",
    suit: "army",
    name: "celestial-knights",
    value: 20,
  },
  {
    id: "army-dwarvish-infantry",
    suit: "army",
    name: "dwarvish-infantry",
    value: 15,
  },
  {
    id: "army-elven-archers",
    suit: "army",
    name: "elven-archers",
    value: 10,
  },
  {
    id: "army-light-calvary",
    suit: "army",
    name: "light-calvary",
    value: 17,
  },
  {
    id: "army-rangers",
    suit: "army",
    name: "rangers",
    value: 5,
  },
  {
    id: "artifact-book-of-changes",
    suit: "artifact",
    name: "book-of-changes",
    value: 3,
  },
  {
    id: "artifact-gem-of-order",
    suit: "artifact",
    name: "gem-of-order",
    value: 5,
  },
  {
    id: "artifact-protection-rune",
    suit: "artifact",
    name: "protection-rune",
    value: 1,
  },
  {
    id: "artifact-shield-of-keth",
    suit: "artifact",
    name: "shield-of-keth",
    value: 4,
  },
  {
    id: "artifact-world-tree",
    suit: "artifact",
    name: "world-tree",
    value: 2,
  },
  {
    id: "beast-basilisk",
    suit: "beast",
    name: "basilisk",
    value: 35,
  },
  {
    id: "beast-dragon",
    suit: "beast",
    name: "dragon",
    value: 30,
  },
  {
    id: "beast-hydra",
    suit: "beast",
    name: "hydra",
    value: 12,
  },
  {
    id: "beast-unicorn",
    suit: "beast",
    name: "unicorn",
    value: 9,
  },
  {
    id: "beast-warhorse",
    suit: "beast",
    name: "warhorse",
    value: 6,
  },
  {
    id: "flame-candle",
    suit: "flame",
    name: "candle",
    value: 2,
  },
  {
    id: "flame-fire-elemental",
    suit: "flame",
    name: "fire-elemental",
    value: 4,
  },
  {
    id: "flame-forge",
    suit: "flame",
    name: "forge",
    value: 9,
  },
  {
    id: "flame-lightning",
    suit: "flame",
    name: "lightning",
    value: 11,
  },
  {
    id: "flame-wildfire",
    suit: "flame",
    name: "wildfire",
    value: 40,
  },
  {
    id: "flood-fountain-of-life",
    suit: "flood",
    name: "fountain-of-life",
    value: 1,
  },
  {
    id: "flood-great-flood",
    suit: "flood",
    name: "great-flood",
    value: 32,
  },
  {
    id: "flood-island",
    suit: "flood",
    name: "island",
    value: 14,
  },
  {
    id: "flood-swamp",
    suit: "flood",
    name: "swamp",
    value: 18,
  },
  {
    id: "flood-water-elemental",
    suit: "flood",
    name: "water-elemental",
    value: 4,
  },
  {
    id: "land-bell-tower",
    suit: "land",
    name: "bell-tower",
    value: 8,
  },
  {
    id: "land-cavern",
    suit: "land",
    name: "cavern",
    value: 6,
  },
  {
    id: "land-earth-elemental",
    suit: "land",
    name: "earth-elemental",
    value: 4,
  },
  {
    id: "land-forest",
    suit: "land",
    name: "forest",
    value: 7,
  },
  {
    id: "land-mountain",
    suit: "land",
    name: "mountain",
    value: 9,
  },
  {
    id: "leader-empress",
    suit: "leader",
    name: "empress",
    value: 15,
  },
  {
    id: "leader-king",
    suit: "leader",
    name: "king",
    value: 8,
  },
  {
    id: "leader-princess",
    suit: "leader",
    name: "princess",
    value: 2,
  },
  {
    id: "leader-queen",
    suit: "leader",
    name: "queen",
    value: 6,
  },
  {
    id: "leader-warlord",
    suit: "leader",
    name: "warlord",
    value: 4,
  },
  {
    id: "weapon-elven-longbow",
    suit: "weapon",
    name: "elven-longbow",
    value: 3,
  },
  {
    id: "weapon-magic-wand",
    suit: "weapon",
    name: "magic-wand",
    value: 1,
  },
  {
    id: "weapon-sword-of-keth",
    suit: "weapon",
    name: "sword-of-keth",
    value: 7,
  },
  {
    id: "weapon-war-dirigible",
    suit: "weapon",
    name: "war-dirigible",
    value: 35,
  },
  {
    id: "weapon-warship",
    suit: "weapon",
    name: "warship",
    value: 23,
  },
  {
    id: "weather-air-elemental",
    suit: "weather",
    name: "air-elemental",
    value: 4,
  },
  {
    id: "weather-blizzard",
    suit: "weather",
    name: "blizzard",
    value: 30,
  },
  {
    id: "weather-rainstorm",
    suit: "weather",
    name: "rainstorm",
    value: 8,
  },
  {
    id: "weather-smoke",
    suit: "weather",
    name: "smoke",
    value: 27,
  },
  {
    id: "weather-whirlwind",
    suit: "weather",
    name: "whirlwind",
    value: 13,
  },
  {
    id: "wild-doppelganger",
    suit: "wild",
    name: "doppelganger",
    value: 0,
  },
  {
    id: "wild-mirage",
    suit: "wild",
    name: "mirage",
    value: 0,
  },
  {
    id: "wild-shapeshifter",
    suit: "wild",
    name: "shapeshifter",
    value: 0,
  },
  {
    id: "wizard-beastmaster",
    suit: "wizard",
    name: "beastmaster",
    value: 9,
  },
  {
    id: "wizard-collector",
    suit: "wizard",
    name: "collector",
    value: 7,
  },
  {
    id: "wizard-enchantress",
    suit: "wizard",
    name: "enchantress",
    value: 5,
  },
  {
    id: "wizard-necromancer",
    suit: "wizard",
    name: "necromancer",
    value: 3,
  },
  {
    id: "wizard-warlock-lord",
    suit: "wizard",
    name: "warlock-lord",
    value: 25
  },
]
