const PUBLIC_TRIGGER_TYPE_ONCE = 'ONCE'
const PUBLIC_TRIGGER_TYPE_NORMAL = 'NORMAL'

const COMBOS = {
  HAND: 'HAND',
  PLAY: 'PLAY',
  DECK: 'DECK',
  BUFFET: 'BUFFET',
  STARTER: 'STARTER'
}

export default {
  PUBLIC_TRIGGER_TYPE_ONCE,
  PUBLIC_TRIGGER_TYPE_NORMAL,
  COMBOS
}
