[
  {
    "uuid": "tkpja98anfe",
    "cost": 2,
    "type": "atkOnce_defGood_tapBad",
    "tap": "damage",
    "__destroyMana": 1,
    "__returnMana": 3,
    "__tapMana": 4.5,
    "ATK": 4,
    "DEF": 2,
    "TAP": "2-"
  },
  {
    "uuid": "bq9v6zr80al",
    "cost": 2,
    "type": "atkOnce_defGood_tapBad",
    "tap": "tap",
    "__destroyMana": 1,
    "__returnMana": 3,
    "__tapMana": 4.5,
    "ATK": 4,
    "DEF": 2,
    "TAP": "2-"
  },
  {
    "uuid": "embbpel3e8e",
    "cost": 3,
    "type": "atkOnce_defGood_tapBad",
    "tap": "draw",
    "__destroyMana": 1.75,
    "__returnMana": 3.75,
    "__tapMana": 5.63,
    "ATK": 5,
    "DEF": 2.5,
    "TAP": "2.5-"
  },
  {
    "uuid": "ilaj7k6x4iq",
    "cost": 5,
    "type": "atkOnce_defGood_tapBad",
    "tap": "destroy",
    "__destroyMana": 3.25,
    "__returnMana": 5.25,
    "__tapMana": 7.88,
    "ATK": 7,
    "DEF": 3.5,
    "TAP": "3.5-"
  },
  {
    "uuid": "1tol0fsj9n1",
    "cost": 1,
    "type": "atkOnce_tapGood_defBad",
    "tap": "untap",
    "__destroyMana": 0.25,
    "__returnMana": 2.25,
    "__tapMana": 3.38,
    "ATK": 3,
    "DEF": "1.5-",
    "TAP": 1.5
  },
  {
    "uuid": "krmavnhiec",
    "cost": 3,
    "type": "atkOnce_tapGood_defBad",
    "tap": "damage",
    "__destroyMana": 1.75,
    "__returnMana": 3.75,
    "__tapMana": 5.63,
    "ATK": 5,
    "DEF": "2.5-",
    "TAP": 2.5
  },
  {
    "uuid": "sbw0h8uysjn",
    "cost": 3,
    "type": "atkOnce_tapGood_defBad",
    "tap": "return",
    "__destroyMana": 1.75,
    "__returnMana": 3.75,
    "__tapMana": 5.63,
    "ATK": 5,
    "DEF": "2.5-",
    "TAP": 2.5
  },
  {
    "uuid": "r7oltmyf0xh",
    "cost": 5,
    "type": "atkOnce_tapGood_defBad",
    "tap": "tap",
    "__destroyMana": 3.25,
    "__returnMana": 5.25,
    "__tapMana": 7.88,
    "ATK": 7,
    "DEF": "3.5-",
    "TAP": 3.5
  },
  {
    "uuid": "h03pbatn61h",
    "cost": 1,
    "type": "defOnce_atkGood_tapBad",
    "tap": "mana",
    "__destroyMana": 0.25,
    "__returnMana": 2.25,
    "__tapMana": 3.38,
    "ATK": 1.5,
    "DEF": 3,
    "TAP": "1.5-"
  },
  {
    "uuid": "q2aqvqbvl8",
    "cost": 2,
    "type": "defOnce_atkGood_tapBad",
    "tap": "damage",
    "__destroyMana": 1,
    "__returnMana": 3,
    "__tapMana": 4.5,
    "ATK": 2,
    "DEF": 4,
    "TAP": "2-"
  },
  {
    "uuid": "a1o3giqj68s",
    "cost": 2,
    "type": "defOnce_atkGood_tapBad",
    "tap": "draw",
    "__destroyMana": 1,
    "__returnMana": 3,
    "__tapMana": 4.5,
    "ATK": 2,
    "DEF": 4,
    "TAP": "2-"
  },
  {
    "uuid": "2hf6fw4dxmd",
    "cost": 2,
    "type": "defOnce_atkGood_tapBad",
    "tap": "return",
    "__destroyMana": 1,
    "__returnMana": 3,
    "__tapMana": 4.5,
    "ATK": 2,
    "DEF": 4,
    "TAP": "2-"
  },
  {
    "uuid": "t5wnk3ng1e",
    "cost": 3,
    "type": "defOnce_atkGood_tapBad",
    "tap": "draw",
    "__destroyMana": 1.75,
    "__returnMana": 3.75,
    "__tapMana": 5.63,
    "ATK": 2.5,
    "DEF": 5,
    "TAP": "2.5-"
  },
  {
    "uuid": "tzwf63m2uec",
    "cost": 3,
    "type": "defOnce_atkGood_tapBad",
    "tap": "tap",
    "__destroyMana": 1.75,
    "__returnMana": 3.75,
    "__tapMana": 5.63,
    "ATK": 2.5,
    "DEF": 5,
    "TAP": "2.5-"
  },
  {
    "uuid": "9q44vh1yh3",
    "cost": 4,
    "type": "defOnce_atkGood_tapBad",
    "tap": "untap",
    "__destroyMana": 2.5,
    "__returnMana": 4.5,
    "__tapMana": 6.75,
    "ATK": 3,
    "DEF": 6,
    "TAP": "3-"
  },
  {
    "uuid": "fber38z1n16",
    "cost": 1,
    "type": "defOnce_tapGood_atkBad",
    "tap": "tap",
    "__destroyMana": 0.25,
    "__returnMana": 2.25,
    "__tapMana": 3.38,
    "ATK": "1.5-",
    "DEF": 3,
    "TAP": 1.5
  },
  {
    "uuid": "bj433r5vvgq",
    "cost": 2,
    "type": "defOnce_tapGood_atkBad",
    "tap": "damage",
    "__destroyMana": 1,
    "__returnMana": 3,
    "__tapMana": 4.5,
    "ATK": "2-",
    "DEF": 4,
    "TAP": 2
  },
  {
    "uuid": "bc239om7eoo",
    "cost": 2,
    "type": "defOnce_tapGood_atkBad",
    "tap": "draw",
    "__destroyMana": 1,
    "__returnMana": 3,
    "__tapMana": 4.5,
    "ATK": "2-",
    "DEF": 4,
    "TAP": 2
  },
  {
    "uuid": "u6rg7gidh8o",
    "cost": 2,
    "type": "defOnce_tapGood_atkBad",
    "tap": "mana",
    "__destroyMana": 1,
    "__returnMana": 3,
    "__tapMana": 4.5,
    "ATK": "2-",
    "DEF": 4,
    "TAP": 2
  },
  {
    "uuid": "laopbbylvv",
    "cost": 3,
    "type": "defOnce_tapGood_atkBad",
    "tap": "destroy",
    "__destroyMana": 1.75,
    "__returnMana": 3.75,
    "__tapMana": 5.63,
    "ATK": "2.5-",
    "DEF": 5,
    "TAP": 2.5
  },
  {
    "uuid": "8o7olpfj96e",
    "cost": 3,
    "type": "defOnce_tapGood_atkBad",
    "tap": "tap",
    "__destroyMana": 1.75,
    "__returnMana": 3.75,
    "__tapMana": 5.63,
    "ATK": "2.5-",
    "DEF": 5,
    "TAP": 2.5
  },
  {
    "uuid": "5sfxhpf48l3",
    "cost": 5,
    "type": "defOnce_tapGood_atkBad",
    "tap": "damage",
    "__destroyMana": 3.25,
    "__returnMana": 5.25,
    "__tapMana": 7.88,
    "ATK": "3.5-",
    "DEF": 7,
    "TAP": 3.5
  },
  {
    "uuid": "1xc73s9vj7m",
    "cost": 6,
    "type": "defOnce_tapGood_atkBad",
    "tap": "draw",
    "__destroyMana": 4,
    "__returnMana": 6,
    "__tapMana": 9,
    "ATK": "4-",
    "DEF": 8,
    "TAP": 4
  },
  {
    "uuid": "qx1foni3bf9",
    "cost": 2,
    "type": "tapOnce_atkGood_defBad",
    "tap": "return",
    "__destroyMana": 4,
    "__returnMana": 6,
    "__tapMana": 9,
    "ATK": 2,
    "DEF": "2-",
    "TAP": 4
  },
  {
    "uuid": "ixhlwzckwb",
    "cost": 2,
    "type": "tapOnce_atkGood_defBad",
    "tap": "untap",
    "__destroyMana": 4,
    "__returnMana": 6,
    "__tapMana": 9,
    "ATK": 2,
    "DEF": "2-",
    "TAP": 4
  },
  {
    "uuid": "zbxbccpxxkh",
    "cost": 3,
    "type": "tapOnce_atkGood_defBad",
    "tap": "damage",
    "__destroyMana": 5.5,
    "__returnMana": 7.5,
    "__tapMana": 11.25,
    "ATK": 2.5,
    "DEF": "2.5-",
    "TAP": 5
  },
  {
    "uuid": "siqwrugdyum",
    "cost": 1,
    "type": "tapOnce_defGood_atkBad",
    "tap": "return",
    "__destroyMana": 2.5,
    "__returnMana": 4.5,
    "__tapMana": 6.75,
    "ATK": "1.5-",
    "DEF": 1.5,
    "TAP": 3
  },
  {
    "uuid": "remtad7c2",
    "cost": 2,
    "type": "tapOnce_defGood_atkBad",
    "tap": "mana",
    "__destroyMana": 4,
    "__returnMana": 6,
    "__tapMana": 9,
    "ATK": "2-",
    "DEF": 2,
    "TAP": 4
  },
  {
    "uuid": "jy87wgzuat",
    "cost": 3,
    "type": "tapOnce_defGood_atkBad",
    "tap": "draw",
    "__destroyMana": 5.5,
    "__returnMana": 7.5,
    "__tapMana": 11.25,
    "ATK": "2.5-",
    "DEF": 2.5,
    "TAP": 5
  },
  {
    "uuid": "096sblekdk6",
    "cost": 4,
    "type": "tapOnce_defGood_atkBad",
    "tap": "destroy",
    "__destroyMana": 7,
    "__returnMana": 9,
    "__tapMana": 13.5,
    "ATK": "3-",
    "DEF": 3,
    "TAP": 6
  }
]
